package com.example.socketio.android;

public interface SocketIOAction
{
	public final String SOCKETIO_PING_SENDER = "ANDROID.SOCKETIO.PING.SENDER";
	public final String SOCKETIO_ERRORMESSAGE_ERRORHANDSHAKING = "ANDROID.SOCKETIO.ERRORMESSAGE.ERRORHANDSHAKING";
	public final String SOCKETIO_ERRORMESSAGE_HEARTBEATTIMEOUT = "ANDROID.SOCKETIO.ERRORMESSAGE.HEARTBEATTIMEOUT";
	public final String SOCKETIO_ERRORMESSAGE_SERVERREJECTCONNECTION = "ANDROID.SOCKETIO.ERRORMESSAGE.SERVERREJECTCONNECTION";

}
